In [1]:
from explaneat.core import backprop
from explaneat.core.backproppop import BackpropPopulation

from explaneat.core.neuralneat import NeuralNeat as NeuralNeat

import random

import torch
import torch.nn as nn
import torch.optim as optim

import neat

from explaneat.core.utility import MethodTimer


from explaneat.core.backprop import NeatNet
from explaneat.core import backprop
from explaneat.core.backproppop import BackpropPopulation
# from explaneat.visualization import visualize
from explaneat.core.experiment import ExperimentReporter

from explaneat.core.neuralneat import NeuralNeat as nneat

import torch.optim as optim

from torch.functional import F

import pprint

pp = pprint.PrettyPrinter(indent=4)







In [5]:
N_GENERATIONS = 50
N_EPOCHS = 25

In [6]:
RANDOM_SEED      = 42
torch.manual_seed(RANDOM_SEED)
random.seed(RANDOM_SEED)


USE_CUDA = torch.cuda.is_available()
USE_CUDA = False
device = torch.device("cuda:1" if USE_CUDA else "cpu")


In [7]:

def xor(a, b, threshold = 0.5):
    response = False
    if a > threshold and b < threshold:
        response = True
    if a < threshold and b > threshold:
        response = True
    # return (1.0, 0.0) if response else (0.0, 1.0)
    return 1.0 if response else 0.0
    

def create_n_points(n, size, min=0.0, max=1.0):
    data = []
    for _ in range(n):
        data.append([
            random.uniform(min, max) for ii in range(size)
        ])

    return data

# correct solution:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference

def overUnder(val, threshold):
    return 1. if val > threshold else 0

xor_inputs = create_n_points(2000, 2, -1, 1)

xor_outputs = [
    [xor(tup[0], tup[1], 0)] for tup in xor_inputs
]

In [8]:
config_path = "./config_xor"
base_config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
                     neat.DefaultSpeciesSet, neat.DefaultStagnation,
                     config_path)

def instantiate_population(config, xs, ys, saveLocation):

    if not os.path.exists(saveLocation):
        os.makedirs(saveLocation)
        
    config.save(os.path.join(saveLocation, 'config.conf'))

    # Create the population, which is the top-level object for a NEAT run.
    with MethodTimer("Backprop everything"):
        p = BackpropPopulation(config, 
                                xs, 
                                ys, 
                                criterion=nn.BCEWithLogitsLoss())

    # Add a stdout reporter to show progress in the terminal.
    p.add_reporter(neat.StdOutReporter(True))
    stats = neat.StatisticsReporter()
    p.add_reporter(stats)
    p.add_reporter(neat.Checkpointer(10, filename_prefix=str(saveLocation) + "checkpoint-" ))
    bpReporter = backprop.BackpropReporter(True)
    p.add_reporter(bpReporter)
    p.add_reporter(ExperimentReporter(saveLocation))
    
    return p

def eval_genomes(genomes, config):
    
    print(genomes)
    loss = nn.BCELoss()
    loss = loss.to(device)
    for genome_id, genome in genomes.items():
        net = neat.nn.FeedForwardNetwork.create(genome, config)
        preds = []
        for xi in xor_inputs:
            preds.append(net.activate(xi))
        genome.fitness = float(1./loss(torch.tensor(preds).to(device), torch.tensor(xor_outputs)))

config = base_config
saveLocation = './'
maxNGenerations = N_GENERATIONS
p = instantiate_population(config, xor_inputs, xor_outputs, saveLocation)
# Run for up to nGenerations generations.
winner = p.run(eval_genomes, maxNGenerations, nEpochs = N_EPOCHS)

g = p.best_genome


The function - Backprop everything - has just started at 1646781910.484052
The function - Backprop everything - took 0.006114006042480469 seconds to complete
The function - generationStart - has just started at 1646781910.490962

 ****** Running generation 0 ****** 

The function - generationStart - took 4.696846008300781e-05 seconds to complete
The function - pre_backprop - has just started at 1646781910.491165
The function - pre_backprop - took 0.0001850128173828125 seconds to complete
The function - backprop - has just started at 1646781910.491362
about to start backprop with 25 epochs
mean improvement: -0.009490729567679794
best improvement: -0.014486616070329195
best loss: 0.4997464744469619
The function - backprop - took 1.3561468124389648 seconds to complete
The function - post_backprop - has just started at 1646781911.84755
The function - post_backprop - took 2.3126602172851562e-05 seconds to complete
The function - evaluate fitness - has just started at 1646781911.847683
{1: <

In [6]:
print(g)

Key: 3008
Fitness: 1.7729040384292603
Nodes:
	0 DefaultNodeGene(key=0, bias=0.11677816134268729, response=1.0, activation=sigmoid, aggregation=sum)
	1 DefaultNodeGene(key=1, bias=-1.406214922688899, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 0), weight=1.0260298180239302, enabled=False)
	DefaultConnectionGene(key=(-2, 1), weight=1.4634387366129928, enabled=True)
	DefaultConnectionGene(key=(-1, 0), weight=0.20870575061507257, enabled=False)
	DefaultConnectionGene(key=(-1, 1), weight=1.6441341531622409, enabled=True)
	DefaultConnectionGene(key=(1, 0), weight=-1.364391716552541, enabled=True)


In [14]:
net = nneat(p.population[1], p.config, criterion=nn.BCEWithLogitsLoss())


KeyError: 'in_weights'

In [8]:
net.genome.connections
# Error is in inputs not being updated with extra info from skip layers

{(-1, 0): <neat.genes.DefaultConnectionGene at 0x7fc1eb18d6d0>,
 (-2, 0): <neat.genes.DefaultConnectionGene at 0x7fc1eb18d730>,
 (-1, 1): <neat.genes.DefaultConnectionGene at 0x7fc1eb18d790>,
 (1, 0): <neat.genes.DefaultConnectionGene at 0x7fc1eb18d7f0>,
 (-2, 1): <neat.genes.DefaultConnectionGene at 0x7fc1eb18d850>}

In [9]:
net.forward(torch.tensor( xor_inputs[:10], dtype=torch.float64) ) [:10]

tensor([[0.4299],
        [0.4410],
        [0.4313],
        [0.4239],
        [0.4191],
        [0.4806],
        [0.4131],
        [0.4498],
        [0.4901],
        [0.4269]], dtype=torch.float64, grad_fn=<SliceBackward0>)

In [10]:
net.forward(torch.tensor( xor_inputs, dtype=torch.float64) )[:20]

tensor([[0.4299],
        [0.4410],
        [0.4313],
        [0.4239],
        [0.4191],
        [0.4806],
        [0.4131],
        [0.4498],
        [0.4901],
        [0.4269],
        [0.4223],
        [0.4343],
        [0.4079],
        [0.4000],
        [0.4174],
        [0.4225],
        [0.4544],
        [0.4820],
        [0.4196],
        [0.4158]], dtype=torch.float64, grad_fn=<SliceBackward0>)

In [11]:
# net.optimiser.zero_grad()

In [12]:
# net.optimise(xor_inputs, xor_outputs)

In [13]:
optimiser = optim.Adadelta(net.parameters())

In [14]:
net.weights

{2: Parameter containing:
 tensor([[ 0.2614],
         [ 0.4419],
         [-1.1644]], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([[2.0501],
         [1.7986]], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)}

In [15]:
optimizer = optimiser
losses = []
for i in range(10000):
    preds = net.forward(torch.tensor( xor_inputs, dtype=torch.float64) )
    loss = F.mse_loss(preds, torch.tensor( xor_outputs, dtype=torch.float64)).sqrt()
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    losses.append(loss)  
losses[-10:]


[tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>),
 tensor(0.3111, dtype=torch.float64, grad_fn=<SqrtBackward0>)]

In [16]:
preds[:10]

tensor([[0.4537],
        [0.1226],
        [0.1333],
        [0.8946],
        [0.0722],
        [0.6352],
        [0.0056],
        [0.8049],
        [0.7974],
        [0.7743]], dtype=torch.float64, grad_fn=<SliceBackward0>)

In [17]:
net.weights

{2: Parameter containing:
 tensor([[  5.9866],
         [  6.1061],
         [-17.6956]], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([[3.2705],
         [3.1963]], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)}

In [18]:
net.layers

{2: {'nodes': {0: {'depth': 2,
    'output_ids': [],
    'input_ids': [-1, -2, 1],
    'depths': [],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 0, 1],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 1],
  'input_shape': 3,
  'weights_shape': (3, 1),
  'out_weights': [],
  'bias': [0.18166490621612177],
  'in_weights': [[0]],
  'input_weights': array([[ 0.26136984],
         [ 0.44193333],
         [-1.16436548]]),
  'input_map': {(-1, 0): (0, 0), (-2, 0): (1, 0), (1, 0): (2, 0)}},
 1: {'nodes': {1: {'depth': 1,
    'output_ids': [0],
    'input_ids': [-1, -2],
    'depths': [],
    'output_layers': [2],
    'needs_skip': False,
    'id': 1,
    'input_layers': [0, 0],
    'skip_layer_input': False,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0],
  'input_

In [19]:
net.node_tracker[0]['depth']

2

In [20]:


reached_nodes = []

node_stack = []

# Instantiate stack with depth==0 nodes
for node_id, node in net.node_tracker.items():
    if node_id < 0:
        node_stack.append(node_id)

while len(node_stack) > 0:
    reached_nodes.append(node_stack[0])
    for node_id in net.node_tracker[node_stack[0]]['output_ids']:
        node_stack.append(node_id)
    del(node_stack[0])

if True:
    print("the reached nodes are")
    print(reached_nodes)


for node_id in net.node_tracker:
    if not node_id in reached_nodes:
        print(reached_nodes)
        print(net.node_tracker)
        print("I can't reach this node {}".format(node_id))

the reached nodes are
[-1, -2, 0, 1, 0, 1, 0, 0]


In [21]:
print(net.genome)

Key: 4642
Fitness: 2.1094460487365723
Nodes:
	0 DefaultNodeGene(key=0, bias=0.18166490621612177, response=1.0, activation=sigmoid, aggregation=sum)
	1 DefaultNodeGene(key=1, bias=-1.0567265402627757, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 0), weight=0.4419333274453102, enabled=True)
	DefaultConnectionGene(key=(-2, 1), weight=1.7986221590262768, enabled=True)
	DefaultConnectionGene(key=(-1, 0), weight=0.26136983756591586, enabled=True)
	DefaultConnectionGene(key=(-1, 1), weight=2.050053457973652, enabled=True)
	DefaultConnectionGene(key=(1, 0), weight=-1.1643654806853805, enabled=True)


In [22]:
net.node_mapping.layers

{2: {'nodes': {0: {'depth': 2,
    'output_ids': [],
    'input_ids': [-1, -2, 1],
    'depths': [1, 1, 2, 2],
    'on_path_to_output': True,
    'on_path_to_input': False,
    'is_input': False,
    'is_output': True,
    'is_valid': True,
    'output_layers': [],
    'input_layers': [0, 0, 1],
    'skips_in': True,
    'skips_out': False,
    'layer': 2,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'layer_activation': 'Sigmoid',
  'input_layers': [0, 1],
  'input_shape': 3,
  'output_shape': 1,
  'weights_shape': (3, 1),
  'input_map': {},
  'shape': (3, 1)},
 1: {'nodes': {1: {'depth': 1,
    'output_ids': [0],
    'input_ids': [-1, -2],
    'depths': [1, 1],
    'on_path_to_output': True,
    'on_path_to_input': True,
    'is_input': False,
    'is_output': False,
    'is_valid': True,
    'output_layers': [2],
    'input_layers': [0, 0],
    'skips_in': False,
    'skips_out': False,
    'layer': 1,
    'layer_index': 0}

In [23]:
for layer_id in sorted (net.node_mapping.layers.keys()):
    layer = net.node_mapping.layers[layer_id]
    print(layer_id)
    print(layer['input_layers'])
    print(layer['shape'])
    print("----")

0
[]
(0, 2)
----
1
[0]
(2, 1)
----
2
[0, 1]
(3, 1)
----


In [24]:
pp.pprint(net.node_mapping.connection_map)

{   (-2, 0): (2, 1, 0),
    (-2, 1): (1, 1, 0),
    (-1, 0): (2, 0, 0),
    (-1, 1): (1, 0, 0),
    (1, 0): (2, 2, 0)}


In [25]:
net.node_mapping.connection_map

{(-1, 0): (2, 0, 0),
 (-2, 0): (2, 1, 0),
 (1, 0): (2, 2, 0),
 (-1, 1): (1, 0, 0),
 (-2, 1): (1, 1, 0)}

In [26]:
pp.pprint(net.genome.connections)

{   (-2, 0): <neat.genes.DefaultConnectionGene object at 0x7fc1eb18d730>,
    (-2, 1): <neat.genes.DefaultConnectionGene object at 0x7fc1eb18d850>,
    (-1, 0): <neat.genes.DefaultConnectionGene object at 0x7fc1eb18d6d0>,
    (-1, 1): <neat.genes.DefaultConnectionGene object at 0x7fc1eb18d790>,
    (1, 0): <neat.genes.DefaultConnectionGene object at 0x7fc1eb18d7f0>}


In [27]:
for connection_id, connection in net.genome.connections.items():
    print(connection_id)
    print(connection.enabled)

(-1, 0)
True
(-2, 0)
True
(-1, 1)
True
(1, 0)
True
(-2, 1)
True
