In [1]:
from __future__ import print_function
import os
import neat

import pandas as pd
import numpy as np
import random

import torch
import torch.nn as nn
import torch.optim as optim


from explaneat.core.backprop import NeatNet
from explaneat.core import backprop
from explaneat.core.backproppop import BackpropPopulation
# from explaneat.visualization import visualize
from explaneat.core.experiment import ExperimentReporter
from explaneat.core.utility import one_hot_encode
from explaneat.core.utility import MethodTimer


from sklearn import datasets, metrics
from sklearn.preprocessing import StandardScaler, normalize, OneHotEncoder
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

from copy import deepcopy

import time
from datetime import datetime

from explaneat.core.neuralneat import NeuralNeat as nneat

In [2]:
RANDOM_SEED      = 42


USE_CUDA = torch.cuda.is_available()
USE_CUDA = False
device = torch.device("cuda:1" if USE_CUDA else "cpu")



In [3]:
torch.cuda.is_available()

False

In [4]:

def xor(a, b, threshold = 0.5):
    response = False
    if a > threshold and b < threshold:
        response = True
    if a < threshold and b > threshold:
        response = True
    # return (1.0, 0.0) if response else (0.0, 1.0)
    return 1.0 if response else 0.0
    

def create_n_points(n, size, min=0.0, max=1.0):
    data = []
    for _ in range(n):
        data.append([
            random.uniform(min, max) for ii in range(size)
        ])

    return data

# correct solution:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference

def overUnder(val, threshold):
    return 1. if val > threshold else 0

xor_inputs = create_n_points(400, 2, -1, 1)

xor_outputs = [
    [xor(tup[0], tup[1], 0)] for tup in xor_inputs
]

In [5]:
xor_inputs[:5]

[[0.06714656611616276, 0.7196194468545101],
 [0.6420591938524554, 0.001618230387546049],
 [-0.9106449283183302, -0.07904534474516067],
 [-0.04362753357092264, 0.6757549534710519],
 [-0.5180374692730203, -0.936631470897298]]

In [6]:
xor_outputs[:5]

[[0.0], [0.0], [0.0], [1.0], [0.0]]

# Set up run


In [7]:
config_path = "./config_xor"
base_config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
                     neat.DefaultSpeciesSet, neat.DefaultStagnation,
                     config_path)

In [8]:
def instantiate_population(config, xs, ys, saveLocation):

    if not os.path.exists(saveLocation):
        os.makedirs(saveLocation)
        
    config.save(os.path.join(saveLocation, 'config.conf'))

    # Create the population, which is the top-level object for a NEAT run.
    with MethodTimer("Backprop everything"):
        p = BackpropPopulation(config, 
                                xs, 
                                ys, 
                                criterion=nn.BCEWithLogitsLoss())

    # Add a stdout reporter to show progress in the terminal.
    p.add_reporter(neat.StdOutReporter(True))
    stats = neat.StatisticsReporter()
    p.add_reporter(stats)
    p.add_reporter(neat.Checkpointer(5, filename_prefix=str(saveLocation) + "checkpoint-" ))
    bpReporter = backprop.BackpropReporter(True)
    p.add_reporter(bpReporter)
    p.add_reporter(ExperimentReporter(saveLocation))
    
    return p

In [9]:
def eval_genomes(genomes, config):
    
    print(genomes)
    loss = nn.BCELoss()
    loss = loss.to(device)
    for genome_id, genome in genomes.items():
        net = neat.nn.FeedForwardNetwork.create(genome, config)
        preds = []
        for xi in xor_inputs:
            preds.append(net.activate(xi))
        genome.fitness = float(1./loss(torch.tensor(preds).to(device), torch.tensor(xor_outputs)))

In [10]:
config = base_config
saveLocation = './'
maxNGenerations = 3
p = instantiate_population(config, xor_inputs, xor_outputs, saveLocation)
# Run for up to nGenerations generations.
winner = p.run(eval_genomes, maxNGenerations, nEpochs = 5)

g = p.best_genome


The function - Backprop everything - has just started at 1615092808.2442229
The function - Backprop everything - took 0.0019390583038330078 seconds to complete
The function - generationStart - has just started at 1615092808.246356

 ****** Running generation 0 ****** 

The function - generationStart - took 2.9802322387695312e-05 seconds to complete
The function - pre_backprop - has just started at 1615092808.246401
The function - pre_backprop - took 3.409385681152344e-05 seconds to complete
The function - backprop - has just started at 1615092808.246444
about to start backprop with 5 epochs
mean improvement: 0.0
best improvement: tensor(0., grad_fn=<SubBackward0>)
best loss: tensor(0.6553, grad_fn=<DivBackward0>)
The function - backprop - took 2.010190010070801 seconds to complete
The function - post_backprop - has just started at 1615092810.256727
The function - post_backprop - took 2.5033950805664062e-05 seconds to complete
The function - evaluate fitness - has just started at 161509

In [11]:
print(g)

Key: 9
Fitness: 1.415993094444275
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.0574650876224041, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 0), weight=0.08104127645492554, enabled=True)


In [12]:
h = deepcopy(g)

In [13]:
print(h)

Key: 9
Fitness: 1.415993094444275
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.0574650876224041, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 0), weight=0.08104127645492554, enabled=True)


In [14]:
h.mutate_add_node(p.config.genome_config)
h.mutate_add_node(p.config.genome_config)
h.mutate_add_node(p.config.genome_config)
h.mutate_add_node(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)

In [15]:
print(h)

Key: 9
Fitness: 1.415993094444275
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.0574650876224041, response=1.0, activation=sigmoid, aggregation=sum)
	2 DefaultNodeGene(key=2, bias=0.04665731895392414, response=1.0, activation=sigmoid, aggregation=sum)
	3 DefaultNodeGene(key=3, bias=1.1647211651589515, response=1.0, activation=sigmoid, aggregation=sum)
	4 DefaultNodeGene(key=4, bias=-0.36676676399489794, response=1.0, activation=sigmoid, aggregation=sum)
	5 DefaultNodeGene(key=5, bias=-0.47366353295619107, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 0), weight=0.08104127645492554, enabled=False)
	DefaultConnectionGene(key=(-2, 2), weight=1.0, enabled=False)
	DefaultConnectionGene(key=(-2, 3), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(-2, 4), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(2, 0), weight=0.08104127645492554, enabled=True)
	DefaultConnectionGene(key=(3, 0), weight=0.08104127645492554, enabled=True)
	DefaultCo

In [16]:
# h.add_connection(p.config.genome_config, 16, 17, 0.2, True)
# h.add_connection(p.config.genome_config, 17, 0, 0.2, True)

In [17]:
print(h)

Key: 9
Fitness: 1.415993094444275
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.0574650876224041, response=1.0, activation=sigmoid, aggregation=sum)
	2 DefaultNodeGene(key=2, bias=0.04665731895392414, response=1.0, activation=sigmoid, aggregation=sum)
	3 DefaultNodeGene(key=3, bias=1.1647211651589515, response=1.0, activation=sigmoid, aggregation=sum)
	4 DefaultNodeGene(key=4, bias=-0.36676676399489794, response=1.0, activation=sigmoid, aggregation=sum)
	5 DefaultNodeGene(key=5, bias=-0.47366353295619107, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 0), weight=0.08104127645492554, enabled=False)
	DefaultConnectionGene(key=(-2, 2), weight=1.0, enabled=False)
	DefaultConnectionGene(key=(-2, 3), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(-2, 4), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(2, 0), weight=0.08104127645492554, enabled=True)
	DefaultConnectionGene(key=(3, 0), weight=0.08104127645492554, enabled=True)
	DefaultCo

In [18]:
p.config.genome_config.input_keys

[-1, -2]

In [19]:
h.nodes

{0: <neat.genes.DefaultNodeGene at 0x7fea5098d2e0>,
 2: <neat.genes.DefaultNodeGene at 0x7fea50996ee0>,
 3: <neat.genes.DefaultNodeGene at 0x7fea50996eb0>,
 4: <neat.genes.DefaultNodeGene at 0x7fea50996f40>,
 5: <neat.genes.DefaultNodeGene at 0x7fea5099e0d0>}

In [20]:
node_tracker = {node_id:{'depth':0, 'output_ids':[], 'input_ids':[]} for node_id in h.nodes}
for node_id in p.config.genome_config.input_keys:
    node_tracker[node_id] = {'depth':0, 'output_ids':[], 'input_ids':[]}
trace_stack = [node_id for node_id in p.config.genome_config.input_keys]

In [21]:
trace_stack

[-1, -2]

In [22]:
node_tracker

{0: {'depth': 0, 'output_ids': [], 'input_ids': []},
 2: {'depth': 0, 'output_ids': [], 'input_ids': []},
 3: {'depth': 0, 'output_ids': [], 'input_ids': []},
 4: {'depth': 0, 'output_ids': [], 'input_ids': []},
 5: {'depth': 0, 'output_ids': [], 'input_ids': []},
 -1: {'depth': 0, 'output_ids': [], 'input_ids': []},
 -2: {'depth': 0, 'output_ids': [], 'input_ids': []}}

In [23]:
for connection in h.connections:
    print(connection)
    node_tracker[connection[0]]['output_ids'].append(connection[1])
    node_tracker[connection[1]]['input_ids'].append(connection[0])

(-2, 0)
(-2, 2)
(2, 0)
(-2, 3)
(3, 0)
(-2, 4)
(4, 2)
(4, 5)
(5, 2)
(4, 0)
(3, 4)


In [24]:
while len(trace_stack) > 0:
    trace = trace_stack[0]
    my_depth = node_tracker[trace]['depth']
    next_depth = my_depth + 1
    for output_id in node_tracker[trace]['output_ids']:
        node_tracker[output_id]['depth'] = max(node_tracker[output_id]['depth'], next_depth)
        trace_stack.append(output_id)
    del(trace_stack[0])

In [25]:
node_tracker

{0: {'depth': 5, 'output_ids': [], 'input_ids': [-2, 2, 3, 4]},
 2: {'depth': 4, 'output_ids': [0], 'input_ids': [-2, 4, 5]},
 3: {'depth': 1, 'output_ids': [0, 4], 'input_ids': [-2]},
 4: {'depth': 2, 'output_ids': [2, 5, 0], 'input_ids': [-2, 3]},
 5: {'depth': 3, 'output_ids': [2], 'input_ids': [4]},
 -1: {'depth': 0, 'output_ids': [], 'input_ids': []},
 -2: {'depth': 0, 'output_ids': [0, 2, 3, 4], 'input_ids': []}}

In [26]:
for node_id, node in node_tracker.items():
    node['output_layers']=[]
    node['needs_skip'] = False
    node['id'] = node_id
    for output_id in node['output_ids']:
        node['output_layers'].append(node_tracker[output_id]['depth'])
        if node_tracker[output_id]['depth'] > (node['depth']+1):
            node['needs_skip'] = True

Create input layer definitions

In [27]:
for node_id, node in node_tracker.items():
    node['input_layers'] = []
    node['skip_layer_input'] = False
    for input_id in node['input_ids']:
        node['input_layers'].append(node_tracker[input_id]['depth'])
        if node_tracker[input_id]['depth'] < (node['depth']-1):
            node['skip_layer_input'] = True

In [28]:
node_tracker

{0: {'depth': 5,
  'output_ids': [],
  'input_ids': [-2, 2, 3, 4],
  'output_layers': [],
  'needs_skip': False,
  'id': 0,
  'input_layers': [0, 4, 1, 2],
  'skip_layer_input': True},
 2: {'depth': 4,
  'output_ids': [0],
  'input_ids': [-2, 4, 5],
  'output_layers': [5],
  'needs_skip': False,
  'id': 2,
  'input_layers': [0, 2, 3],
  'skip_layer_input': True},
 3: {'depth': 1,
  'output_ids': [0, 4],
  'input_ids': [-2],
  'output_layers': [5, 2],
  'needs_skip': True,
  'id': 3,
  'input_layers': [0],
  'skip_layer_input': False},
 4: {'depth': 2,
  'output_ids': [2, 5, 0],
  'input_ids': [-2, 3],
  'output_layers': [4, 3, 5],
  'needs_skip': True,
  'id': 4,
  'input_layers': [0, 1],
  'skip_layer_input': True},
 5: {'depth': 3,
  'output_ids': [2],
  'input_ids': [4],
  'output_layers': [4],
  'needs_skip': False,
  'id': 5,
  'input_layers': [2],
  'skip_layer_input': False},
 -1: {'depth': 0,
  'output_ids': [],
  'input_ids': [],
  'output_layers': [],
  'needs_skip': False,
 

In [29]:
layers = {}
for node_id, node in node_tracker.items():
    if not node['depth'] in layers:
        layers[node['depth']] = {
            'nodes':{node_id:node}
        }
    else:
        layers[node['depth']]['nodes'][node_id] = node
        
# Ensure all nodes have a layer index
for layer_id, layer in layers.items():
    layer_index = 0
    for node_id, node in layer['nodes'].items():
        node['layer_index'] = layer_index
        layer_index += 1
        
        
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-2, 2, 3, 4],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 4, 1, 2],
    'skip_layer_input': True,
    'layer_index': 0}}},
 4: {'nodes': {2: {'depth': 4,
    'output_ids': [0],
    'input_ids': [-2, 4, 5],
    'output_layers': [5],
    'needs_skip': False,
    'id': 2,
    'input_layers': [0, 2, 3],
    'skip_layer_input': True,
    'layer_index': 0}}},
 1: {'nodes': {3: {'depth': 1,
    'output_ids': [0, 4],
    'input_ids': [-2],
    'output_layers': [5, 2],
    'needs_skip': True,
    'id': 3,
    'input_layers': [0],
    'skip_layer_input': False,
    'layer_index': 0}}},
 2: {'nodes': {4: {'depth': 2,
    'output_ids': [2, 5, 0],
    'input_ids': [-2, 3],
    'output_layers': [4, 3, 5],
    'needs_skip': True,
    'id': 4,
    'input_layers': [0, 1],
    'skip_layer_input': True,
    'layer_index': 0}}},
 3: {'nodes': {5: {'depth': 3,
    'output_ids': [2],
    'input_

In [30]:

LAYER_TYPE_CONNECTED = "CONNECTED"
LAYER_TYPE_INPUT = "INPUT"
LAYER_TYPE_OUTPUT = "OUTPUT"
for layer_id, layer in layers.items():
    layer['is_output_layer'] = False
    layer['is_input_layer'] = False
    layer['layer_type'] = LAYER_TYPE_CONNECTED
    # If I have the output node in me, then I am an output
    if 0 in layer['nodes']:
        layer['is_output_layer'] = True
        layer['layer_type'] = LAYER_TYPE_OUTPUT

    # If I have the first input in me, then I am the input
    if -1 in layer['nodes']:
        layer['is_input_layer'] = True
        layer['layer_type'] = LAYER_TYPE_INPUT
    biases = []

    layer['input_layers'] = []
    ## Compute the shape of required inputs
    for node_id, node in layer['nodes'].items():
        for in_layer in node['input_layers']:
            if in_layer not in layer['input_layers']:
                layer['input_layers'].append(in_layer)
    layer['input_layers'].sort()
    layer['input_shape'] = sum(len(layers[jj]['nodes']) for jj in layer['input_layers'])
    layer['weights_shape'] = (layer['input_shape'], len(layer['nodes']))


    # Handle output layer "edge" case
    if layer['is_output_layer']:
        layer['out_weights'] = []
        layer['bias'] = [h.nodes[node_id].bias for node_id, node in layer['nodes'].items()]
        layer['in_weights'] = [[0 for __ in layers[layer_id-1]['nodes']] for _ in layer['nodes']]
    # Handle input layer "edge" case
    elif layer['is_input_layer']:
        layer['in_weights'] = []
        layer['bias'] = []
        layer['out_weights'] = [[0 for __ in layers[layer_id+1]['nodes']] for _ in layer['nodes']]
    # Handle generic case
    else:
        layer['out_weights'] = [[0 for __ in layers[layer_id+1]['nodes']] for _ in layer['nodes']]
        layer['in_weights'] = [[0 for __ in layers[layer_id-1]['nodes']] for _ in layer['nodes']]

        layer['bias'] = [h.nodes[node_id].bias for node_id, node in layer['nodes'].items()]
        # else:
            # layer['bias'] = [0 for _ in layer['nodes']]
    
    layer_index = 0          
    for node_id, node in layer['nodes'].items():
        node['layer_index'] = layer_index
        layer_index += 1

#################################################
#################################################
#################################################
        ### POSSIBLY NEED THIS
        # if node['id'] < 0:
        #     biases.append(1)
        # else:
        #     biases.append(h.nodes[node['id']].bias)
        # for output_id in node['output_ids']:
        #     if (node['id'], output_id) in h.connections:
        #         if output_id in layers[layer_id + 1]['nodes']:
        #             layer['out_weights'][node['layer_index']][layers[layer_id + 1]['nodes'][output_id]['layer_index']] = h.connections[(node['id'], output_id)].weight
        #         else:
        #             # TODO: this is a skip layer to deal with
        #             pass
        #     else:
        #         # this is not a connection that exists, so default of 0 holds
        #         pass
        # for input_id in node['input_ids']:
        #     if (input_id, node['id']) in h.connections:
        #         if input_id in layers[layer_id - 1]['nodes']:
        #             layer['in_weights'][node['layer_index']][layers[layer_id -1]['nodes'][input_id]['layer_index']] = h.connections[(input_id, node['id'])].weight
        #         else:
        #             # TODO: this is a skip layer to deal with
        #             pass
        #     else:
        #         # this is not a connection that exists, so default of 0 holds
        #         pass
        #################################################
            ### END OF POSSIBLY NEEDING THIS
    #################################################
    #################################################
    #################################################
    #################################################


    # layer['out_tensor'] = torch.tensor(layer['out_weights'])
    # layer['bias'] = torch.tensor(layer['bias'])
    # layer['out_tensor_shape'] = layer['out_tensor'].shape
    # layer['in_tensor'] = torch.tensor(layer['in_weights'])
    # layer['in_tensor_shape'] = layer['in_tensor'].shape



    # Set up current weights
    layer['input_weights'] = np.zeros(layer['weights_shape'])
    layer_offset = 0
    # Check every layer and every node for connections
    print("my layer id is %s" % (layer_id))
    for input_layer_id in layer['input_layers']:
        input_layer = layers[input_layer_id]
        for node_id, node in input_layer['nodes'].items():
            for node_output_id in node['output_ids']:
                if node_output_id in layer['nodes']:
                    node_output = layer['nodes'][node_output_id]
                    # I HAVE THIS NODE!
                    # What is it's weight?
                    connection = h.connections[(node_id, node_output_id)]
                    print(connection)

                    if not connection.enabled:
                        continue
                    connection_weight = connection.weight
                    print(connection_weight)

                    in_weight_location = layer_offset + node['layer_index']
                    out_weight_location = node_output['layer_index']
                    print('location is')
                    print((out_weight_location, in_weight_location))
                    layer['input_weights'][in_weight_location][out_weight_location] = connection_weight
        layer_offset += len(input_layer['nodes'])

my layer id is 5
DefaultConnectionGene(key=(-2, 0), weight=0.08104127645492554, enabled=False)
DefaultConnectionGene(key=(3, 0), weight=0.08104127645492554, enabled=True)
0.08104127645492554
location is
(0, 2)
DefaultConnectionGene(key=(4, 0), weight=-0.7558365840995874, enabled=True)
-0.7558365840995874
location is
(0, 3)
DefaultConnectionGene(key=(2, 0), weight=0.08104127645492554, enabled=True)
0.08104127645492554
location is
(0, 4)
my layer id is 4
DefaultConnectionGene(key=(-2, 2), weight=1.0, enabled=False)
DefaultConnectionGene(key=(4, 2), weight=1.0, enabled=False)
DefaultConnectionGene(key=(5, 2), weight=1.0, enabled=True)
1.0
location is
(0, 3)
my layer id is 1
DefaultConnectionGene(key=(-2, 3), weight=1.0, enabled=True)
1.0
location is
(0, 1)
my layer id is 2
DefaultConnectionGene(key=(-2, 4), weight=1.0, enabled=True)
1.0
location is
(0, 1)
DefaultConnectionGene(key=(3, 4), weight=-0.3495623860260543, enabled=True)
-0.3495623860260543
location is
(0, 2)
my layer id is 3
Def

In [31]:
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-2, 2, 3, 4],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 4, 1, 2],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 1, 2, 4],
  'input_shape': 5,
  'weights_shape': (5, 1),
  'out_weights': [],
  'bias': [-0.0574650876224041],
  'in_weights': [[0]],
  'input_weights': array([[ 0.        ],
         [ 0.        ],
         [ 0.08104128],
         [-0.75583658],
         [ 0.08104128]])},
 4: {'nodes': {2: {'depth': 4,
    'output_ids': [0],
    'input_ids': [-2, 4, 5],
    'output_layers': [5],
    'needs_skip': False,
    'id': 2,
    'input_layers': [0, 2, 3],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0, 2, 3],
  'input_shape': 4,
  'weights_shape': (4, 

Add in computation of skip layers

In [32]:
layers[2]

{'nodes': {4: {'depth': 2,
   'output_ids': [2, 5, 0],
   'input_ids': [-2, 3],
   'output_layers': [4, 3, 5],
   'needs_skip': True,
   'id': 4,
   'input_layers': [0, 1],
   'skip_layer_input': True,
   'layer_index': 0}},
 'is_output_layer': False,
 'is_input_layer': False,
 'layer_type': 'CONNECTED',
 'input_layers': [0, 1],
 'input_shape': 3,
 'weights_shape': (3, 1),
 'out_weights': [[0]],
 'in_weights': [[0]],
 'bias': [-0.36676676399489794],
 'input_weights': array([[ 0.        ],
        [ 1.        ],
        [-0.34956239]])}

In [33]:
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-2, 2, 3, 4],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 4, 1, 2],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 1, 2, 4],
  'input_shape': 5,
  'weights_shape': (5, 1),
  'out_weights': [],
  'bias': [-0.0574650876224041],
  'in_weights': [[0]],
  'input_weights': array([[ 0.        ],
         [ 0.        ],
         [ 0.08104128],
         [-0.75583658],
         [ 0.08104128]])},
 4: {'nodes': {2: {'depth': 4,
    'output_ids': [0],
    'input_ids': [-2, 4, 5],
    'output_layers': [5],
    'needs_skip': False,
    'id': 2,
    'input_layers': [0, 2, 3],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0, 2, 3],
  'input_shape': 4,
  'weights_shape': (4, 

The question is, how do you code the operations to dynamically create the
NN? You need to be able to do the right things in the right order. You have
a list of possible operations:
* Matrix multiple
* Concatenate (for skip layers)
* Matrix addition (for biases)
* Output

The order of operations in each layer is:

1. Concatenate input tensors
2. Matrix multiply input tensors with weights
3. Add bias tensors
4. Apply activation function

I.e., `output = f(cat(inputs) + bias)` for a given activation function f

These computations can be computed back-to-front, and then executed forward

In [34]:
ACTIVATE_OPERATION = "ACTIVATE"
OUTPUT_OPERATION = "OUTPUT"
TENADD_OPERATION = "TENADD" # Tensor ADD
ADD_BIAS_OPERATION = "BIASADD"
TENMUL_OPERATION = "TENMUL"
TENCAT_OPERATION = "TENCAT"
order_of_operations = []

# for layer_id, layer in layers.items():
#     print(layer)
#     # Output for final layer
#     if layer['is_output_layer']:
#         order_of_operations.append(OUTPUT_OPERATION)
#     # Activate
#     order_of_operations.append(ACTIVATE_OPERATION)
#     # Add Bias
#     order_of_operations.append(ADD_BIAS_OPERATION)
#     # Matrix Multiply weights

    


#     print(order_of_operations)

#     break

for layer_id in range(len(layers)):
    layer = layers[layer_id]
    print(layer)

{'nodes': {-1: {'depth': 0, 'output_ids': [], 'input_ids': [], 'output_layers': [], 'needs_skip': False, 'id': -1, 'input_layers': [], 'skip_layer_input': False, 'layer_index': 0}, -2: {'depth': 0, 'output_ids': [0, 2, 3, 4], 'input_ids': [], 'output_layers': [5, 4, 1, 2], 'needs_skip': True, 'id': -2, 'input_layers': [], 'skip_layer_input': False, 'layer_index': 1}}, 'is_output_layer': False, 'is_input_layer': True, 'layer_type': 'INPUT', 'input_layers': [], 'input_shape': 0, 'weights_shape': (0, 2), 'in_weights': [], 'bias': [], 'out_weights': [[0], [0]], 'input_weights': array([], shape=(0, 2), dtype=float64)}
{'nodes': {3: {'depth': 1, 'output_ids': [0, 4], 'input_ids': [-2], 'output_layers': [5, 2], 'needs_skip': True, 'id': 3, 'input_layers': [0], 'skip_layer_input': False, 'layer_index': 0}}, 'is_output_layer': False, 'is_input_layer': False, 'layer_type': 'CONNECTED', 'input_layers': [0], 'input_shape': 2, 'weights_shape': (2, 1), 'out_weights': [[0]], 'in_weights': [[0, 0]], '

In [35]:
a = torch.randn(2,3)
b = torch.randn(3, 1)
c = torch.matmul(a, b)

In [36]:
c

tensor([[0.0585],
        [0.1552]])

In [37]:
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-2, 2, 3, 4],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 4, 1, 2],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 1, 2, 4],
  'input_shape': 5,
  'weights_shape': (5, 1),
  'out_weights': [],
  'bias': [-0.0574650876224041],
  'in_weights': [[0]],
  'input_weights': array([[ 0.        ],
         [ 0.        ],
         [ 0.08104128],
         [-0.75583658],
         [ 0.08104128]])},
 4: {'nodes': {2: {'depth': 4,
    'output_ids': [0],
    'input_ids': [-2, 4, 5],
    'output_layers': [5],
    'needs_skip': False,
    'id': 2,
    'input_layers': [0, 2, 3],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0, 2, 3],
  'input_shape': 4,
  'weights_shape': (4, 

In [38]:
x_input = nn.Parameter(torch.tensor([0.3, 0.4], dtype=torch.float64))

In [39]:
class Net(nn.Module):
    def __init__(self, layers):
        super(Net, self).__init__()  # just run the init of parent class (nn.Module)
        self.weights = {layer_id: self._tt(layer['input_weights'].copy()) for layer_id, layer in layers.items()}
        self.biases = {layer_id: self._tt(layer['bias'].copy()) for layer_id, layer in layers.items()}
        self.layer_types = {layer_id: layer['layer_type'] for layer_id, layer in layers.items()}
        self.layer_inputs = {layer_id: layer['input_layers'] for layer_id, layer in layers.items()}
        self.n_layers = len(layers)

        self._outputs = None

        for w_id, w in self.weights.items():
            self.register_parameter(name ="weight_%s"%w_id, param=w)

        for b_id, b in self.biases.items():
            self.register_parameter(name = "bias_%s"%b_id, param=b)

        # x = F.relu(self.fc1(x))

        # self.fc2 = nn.Linear(512, 10)

    @staticmethod
    def _tt(mat):
        return torch.nn.Parameter(torch.tensor(mat,dtype=torch.float64), requires_grad=True)
    def forward(self, x):
        # print("running forward")
        self._outputs = {}
        for layer_id in range(self.n_layers):
            layer_input = None
            layer_type = self.layer_types[layer_id]

            # print(layer_id)
            # print(layer_type)

            if layer_type == LAYER_TYPE_INPUT:
                self._outputs[layer_id] = x
                continue
            if layer_type == LAYER_TYPE_CONNECTED:
                layer_input = torch.cat([self._outputs[ii] for ii in self.layer_inputs[layer_id]])
            if layer_type == LAYER_TYPE_OUTPUT:
                layer_input = torch.cat([self._outputs[ii] for ii in self.layer_inputs[layer_id]])

            # print(layer_input)
            # print(self.weights[layer_id])
            # print(self.biases[layer_id])

            self._outputs[layer_id] = torch.sigmoid( torch.matmul(layer_input, self.weights[layer_id]) + self.biases[layer_id] )

            if layer_type == LAYER_TYPE_OUTPUT:
                return self._outputs[layer_id]


In [40]:
net = Net(layers)

In [41]:
net.biases

{5: Parameter containing:
 tensor([-0.0575], dtype=torch.float64, requires_grad=True),
 4: Parameter containing:
 tensor([0.0467], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([1.1647], dtype=torch.float64, requires_grad=True),
 2: Parameter containing:
 tensor([-0.3668], dtype=torch.float64, requires_grad=True),
 3: Parameter containing:
 tensor([-0.4737], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], dtype=torch.float64, requires_grad=True)}

In [42]:
net._outputs

In [43]:
result = net.forward(x_input)
result

tensor([0.4331], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [44]:
expected_result = torch.tensor(xor(x_input[0], x_input[1]))
expected_result

tensor(0.)

In [45]:
learning_rate = 0.1
# x_input = torch.randn(1, 1, 2, dtype=torch.float64)
with MethodTimer('benchmark'):

    for k in range(25):
        for n in range(400):
            x_input = nn.Parameter(torch.tensor([np.random.rand(), np.random.rand()], dtype=torch.float64))


            result = net.forward(x_input)
            expected_result = torch.tensor(xor(x_input[0], x_input[1]), dtype=torch.float64)
            # print(x_input)
            # print(expected_result)
            # print(result)
            loss_fn = torch.nn.MSELoss(reduction='sum')
            loss = loss_fn(result, expected_result)
            net.zero_grad()
            loss.backward()
            with torch.no_grad():
                # for parameter in net.parameters():
                    # parameter.data -= learning_rate*parameter.grad.data
                    # weight -= learning_rate * weight.grad
                for  w_id, weight in net.weights.items():
                    try:
                        weight -= learning_rate * weight.grad
                    except TypeError:
                        continue
                for  b_id, bias in net.biases.items():
                    try:
                        bias -= learning_rate * bias.grad
                    except TypeError:
                        continue





The function - benchmark - has just started at 1615092814.643156
The function - benchmark - took 5.848366022109985 seconds to complete


In [46]:
# net(torch.tensor(xor_inputs, dtype=torch.float64))

In [47]:
net.biases[1].grad

tensor([0.0083], dtype=torch.float64)

In [48]:
result

tensor([0.4844], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [49]:
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)


In [50]:
optimizer.zero_grad()
output = net(x_input)
loss = loss_fn(result, expected_result)


In [51]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 0.1315],
        [-0.1235],
        [ 0.0934],
        [-0.5734],
        [ 0.0732]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.1986],
        [-0.2043],
        [-0.1504],
        [ 0.8159]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.0614],
        [0.8300]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.1794],
        [ 0.8517],
        [-0.6349]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.9659]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0297], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.3506], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.8202], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.7256], dtype=torch.float64, requires

In [52]:
myW = net.weights[1]

In [53]:
myW

Parameter containing:
tensor([[0.0614],
        [0.8300]], dtype=torch.float64, requires_grad=True)

In [54]:
loss

tensor(0.2346, dtype=torch.float64, grad_fn=<MseLossBackward>)

In [55]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 0.1315],
        [-0.1235],
        [ 0.0934],
        [-0.5734],
        [ 0.0732]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.1986],
        [-0.2043],
        [-0.1504],
        [ 0.8159]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.0614],
        [0.8300]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.1794],
        [ 0.8517],
        [-0.6349]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.9659]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0297], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.3506], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.8202], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.7256], dtype=torch.float64, requires

In [56]:
net.weights

{5: Parameter containing:
 tensor([[ 0.1315],
         [-0.1235],
         [ 0.0934],
         [-0.5734],
         [ 0.0732]], dtype=torch.float64, requires_grad=True),
 4: Parameter containing:
 tensor([[-0.1986],
         [-0.2043],
         [-0.1504],
         [ 0.8159]], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([[0.0614],
         [0.8300]], dtype=torch.float64, requires_grad=True),
 2: Parameter containing:
 tensor([[ 0.1794],
         [ 0.8517],
         [-0.6349]], dtype=torch.float64, requires_grad=True),
 3: Parameter containing:
 tensor([[0.9659]], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)}

In [57]:
net._outputs

{0: Parameter containing:
 tensor([0.2095, 0.3605], dtype=torch.float64, requires_grad=True),
 1: tensor([0.7562], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 2: tensor([0.2971], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 3: tensor([0.4314], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 4: tensor([0.4604], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 5: tensor([0.4719], dtype=torch.float64, grad_fn=<SigmoidBackward>)}

In [58]:
data = torch.rand(1, 1,2, dtype=torch.float64)
label = [xor(val[0][0], val[0][1]) for val in data]


In [62]:
# net(data)

In [63]:
# I.e., `output = f(cat(inputs) + bias)` for a given activation function f

def forward(layers, x):
    layer_outputs = {}
    curr_value = x
    for ii in range(len(layers)):
        print(ii)
        layer = layers[ii]
        if layer['is_output_layer']:
            # return curr_value
            return(layer_outputs)
        input_layers = [layer_outputs[layer_id] for layer_id in layer['input_layers']]
    return(layer_outputs)
        # layer_outputs[ii] = torch.relu(
        #     torch.add(
        #         torch.matmul(
        #             torch.cat(layer['input_layers']),
        #             layer['weights']

        #         ),
        #         layer['bias']
        #     )
        # )
        # curr_value = torch.sigmoid(torch.matmul(curr_value + layers[ii]['bias'], layers[ii]['out_tensor']) )

In [64]:
# forward(layers, x_input)

In [65]:
h.nodes[0].bias

-0.0574650876224041

In [66]:
with MethodTimer('Parse NNEAT'):
    myNeat = nneat(h, p.config)

The function - Parse NNEAT - has just started at 1615092850.771071
The function - Parse NNEAT - took 0.001669168472290039 seconds to complete


In [67]:
myNeat.forward(x_input)

tensor([0.4347], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [68]:
learning_rate = 0.1
# x_input = torch.randn(1, 1, 2, dtype=torch.float64)
with MethodTimer('Backprop benchmark (10k inputs)'):

    for k in range(25):
        for n in range(400):
            x_input = nn.Parameter(torch.tensor([np.random.rand(), np.random.rand()], dtype=torch.float64))


            result = myNeat.forward(x_input)
            expected_result = torch.tensor(xor(x_input[0], x_input[1]), dtype=torch.float64)
            # print(x_input)
            # print(expected_result)
            # print(result)
            loss_fn = torch.nn.MSELoss(reduction='sum')
            loss = loss_fn(result, expected_result)
            myNeat.zero_grad()
            loss.backward()
            with torch.no_grad():
                # for parameter in net.parameters():
                    # try:
                    #     parameter.data -= learning_rate*parameter.grad.data
                    # except AttributeError:
                    #     continue
                    # weight -= learning_rate * weight.grad
                for  w_id, weight in net.weights.items():
                    try:
                        weight -= learning_rate * weight.grad
                    except TypeError:
                        continue
                for  b_id, bias in net.biases.items():
                    try:
                        bias -= learning_rate * bias.grad
                    except TypeError:
                        continue



The function - Backprop benchmark (10k inputs) - has just started at 1615092852.182579
The function - Backprop benchmark (10k inputs) - took 5.201025009155273 seconds to complete


In [69]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[ 0.1315],
        [-0.1235],
        [ 0.0934],
        [-0.5734],
        [ 0.0732]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.1986],
        [-0.2043],
        [-0.1504],
        [ 0.8159]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.0614],
        [0.8300]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.1794],
        [ 0.8517],
        [-0.6349]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.9659]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0297], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.3506], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.8202], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.7256], dtype=torch.float64, requires

In [71]:
myNeat.genome

AttributeError: 'NeuralNeat' object has no attribute 'genome'