In [1]:
from __future__ import print_function
import os
import neat

import pandas as pd
import numpy as np
import random

import torch
import torch.nn as nn
import torch.optim as optim


from explaneat.core.backprop import NeatNet
from explaneat.core import backprop
from explaneat.core.backproppop import BackpropPopulation
# from explaneat.visualization import visualize
from explaneat.core.experiment import ExperimentReporter
from explaneat.core.utility import one_hot_encode
from explaneat.core.utility import MethodTimer


from sklearn import datasets, metrics
from sklearn.preprocessing import StandardScaler, normalize, OneHotEncoder
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

from copy import deepcopy

import time
from datetime import datetime

from explaneat.core.neuralneat import NeuralNeat as nneat

In [2]:
RANDOM_SEED      = 42


USE_CUDA = torch.cuda.is_available()
USE_CUDA = False
device = torch.device("cuda:1" if USE_CUDA else "cpu")



In [3]:
torch.cuda.is_available()

False

In [4]:

def xor(a, b, threshold = 0.5):
    response = False
    if a > threshold and b < threshold:
        response = True
    if a < threshold and b > threshold:
        response = True
    # return (1.0, 0.0) if response else (0.0, 1.0)
    return 1.0 if response else 0.0
    

def create_n_points(n, size, min=0.0, max=1.0):
    data = []
    for _ in range(n):
        data.append([
            random.uniform(min, max) for ii in range(size)
        ])

    return data

# correct solution:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference

def overUnder(val, threshold):
    return 1. if val > threshold else 0

xor_inputs = create_n_points(400, 2, -1, 1)

xor_outputs = [
    [xor(tup[0], tup[1], 0)] for tup in xor_inputs
]

In [5]:
xor_inputs[:5]

[[-0.08839266921885658, -0.3375986658394883],
 [-0.9585117636795317, -0.37022002011608346],
 [-0.28938596485268375, 0.24530099973869124],
 [0.7532001535603277, -0.7756349679726384],
 [0.7165699772199294, -0.7368569121478801]]

In [6]:
xor_outputs[:5]

[[0.0], [0.0], [1.0], [1.0], [1.0]]

# Set up run


In [7]:
config_path = "./config_xor"
base_config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction,
                     neat.DefaultSpeciesSet, neat.DefaultStagnation,
                     config_path)

In [8]:
def instantiate_population(config, xs, ys, saveLocation):

    if not os.path.exists(saveLocation):
        os.makedirs(saveLocation)
        
    config.save(os.path.join(saveLocation, 'config.conf'))

    # Create the population, which is the top-level object for a NEAT run.
    with MethodTimer("Backprop everything"):
        p = BackpropPopulation(config, 
                                xs, 
                                ys, 
                                criterion=nn.BCEWithLogitsLoss())

    # Add a stdout reporter to show progress in the terminal.
    p.add_reporter(neat.StdOutReporter(True))
    stats = neat.StatisticsReporter()
    p.add_reporter(stats)
    p.add_reporter(neat.Checkpointer(5, filename_prefix=str(saveLocation) + "checkpoint-" ))
    bpReporter = backprop.BackpropReporter(True)
    p.add_reporter(bpReporter)
    p.add_reporter(ExperimentReporter(saveLocation))
    
    return p

In [9]:
def eval_genomes(genomes, config):
    
    print(genomes)
    loss = nn.BCELoss()
    loss = loss.to(device)
    for genome_id, genome in genomes.items():
        net = neat.nn.FeedForwardNetwork.create(genome, config)
        preds = []
        for xi in xor_inputs:
            preds.append(net.activate(xi))
        genome.fitness = float(1./loss(torch.tensor(preds).to(device), torch.tensor(xor_outputs)))

In [10]:
config = base_config
saveLocation = './'
maxNGenerations = 3
p = instantiate_population(config, xor_inputs, xor_outputs, saveLocation)
# Run for up to nGenerations generations.
winner = p.run(eval_genomes, maxNGenerations, nEpochs = 5)

g = p.best_genome


The function - Backprop everything - has just started at 1615094965.3835578
The function - Backprop everything - took 0.0008959770202636719 seconds to complete
The function - generationStart - has just started at 1615094965.3847558

 ****** Running generation 0 ****** 

The function - generationStart - took 0.00010132789611816406 seconds to complete
The function - pre_backprop - has just started at 1615094965.384872
The function - pre_backprop - took 2.8133392333984375e-05 seconds to complete
The function - backprop - has just started at 1615094965.3849149
about to start backprop with 5 epochs
mean improvement: 0.0
best improvement: tensor(0., grad_fn=<SubBackward0>)
best loss: tensor(0.6943, grad_fn=<DivBackward0>)
The function - backprop - took 2.054965019226074 seconds to complete
The function - post_backprop - has just started at 1615094967.440008
The function - post_backprop - took 2.7179718017578125e-05 seconds to complete
The function - evaluate fitness - has just started at 161

In [11]:
print(g)

Key: 9
Fitness: 1.0971912145614624
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.4006558060646057, response=1.0, activation=sigmoid, aggregation=sum)
	1 DefaultNodeGene(key=1, bias=1.2642592191696167, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 1), weight=0.5530250668525696, enabled=True)
	DefaultConnectionGene(key=(-1, 0), weight=-0.1703117936849594, enabled=True)
	DefaultConnectionGene(key=(1, 0), weight=0.1489894688129425, enabled=True)


In [12]:
h = deepcopy(g)

In [13]:
print(h)

Key: 9
Fitness: 1.0971912145614624
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.4006558060646057, response=1.0, activation=sigmoid, aggregation=sum)
	1 DefaultNodeGene(key=1, bias=1.2642592191696167, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 1), weight=0.5530250668525696, enabled=True)
	DefaultConnectionGene(key=(-1, 0), weight=-0.1703117936849594, enabled=True)
	DefaultConnectionGene(key=(1, 0), weight=0.1489894688129425, enabled=True)


In [14]:
h.mutate_add_node(p.config.genome_config)
h.mutate_add_node(p.config.genome_config)
h.mutate_add_node(p.config.genome_config)
h.mutate_add_node(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)
h.mutate_add_connection(p.config.genome_config)

In [15]:
print(h)

Key: 9
Fitness: 1.0971912145614624
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.4006558060646057, response=1.0, activation=sigmoid, aggregation=sum)
	1 DefaultNodeGene(key=1, bias=1.2642592191696167, response=1.0, activation=sigmoid, aggregation=sum)
	4 DefaultNodeGene(key=4, bias=-0.8663857890656896, response=1.0, activation=sigmoid, aggregation=sum)
	5 DefaultNodeGene(key=5, bias=2.458661014796236, response=1.0, activation=sigmoid, aggregation=sum)
	6 DefaultNodeGene(key=6, bias=-1.1082741878131992, response=1.0, activation=sigmoid, aggregation=sum)
	7 DefaultNodeGene(key=7, bias=0.03375522113074291, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 1), weight=0.5530250668525696, enabled=False)
	DefaultConnectionGene(key=(-2, 4), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(-2, 5), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(-1, 0), weight=-0.1703117936849594, enabled=True)
	DefaultConnectionGene(key=(-1, 4), weight=0.91513

In [16]:
# h.add_connection(p.config.genome_config, 16, 17, 0.2, True)
# h.add_connection(p.config.genome_config, 17, 0, 0.2, True)

In [17]:
print(h)

Key: 9
Fitness: 1.0971912145614624
Nodes:
	0 DefaultNodeGene(key=0, bias=-0.4006558060646057, response=1.0, activation=sigmoid, aggregation=sum)
	1 DefaultNodeGene(key=1, bias=1.2642592191696167, response=1.0, activation=sigmoid, aggregation=sum)
	4 DefaultNodeGene(key=4, bias=-0.8663857890656896, response=1.0, activation=sigmoid, aggregation=sum)
	5 DefaultNodeGene(key=5, bias=2.458661014796236, response=1.0, activation=sigmoid, aggregation=sum)
	6 DefaultNodeGene(key=6, bias=-1.1082741878131992, response=1.0, activation=sigmoid, aggregation=sum)
	7 DefaultNodeGene(key=7, bias=0.03375522113074291, response=1.0, activation=sigmoid, aggregation=sum)
Connections:
	DefaultConnectionGene(key=(-2, 1), weight=0.5530250668525696, enabled=False)
	DefaultConnectionGene(key=(-2, 4), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(-2, 5), weight=1.0, enabled=True)
	DefaultConnectionGene(key=(-1, 0), weight=-0.1703117936849594, enabled=True)
	DefaultConnectionGene(key=(-1, 4), weight=0.91513

In [18]:
p.config.genome_config.input_keys

[-1, -2]

In [19]:
h.nodes

{0: <neat.genes.DefaultNodeGene at 0x7fa161909790>,
 1: <neat.genes.DefaultNodeGene at 0x7fa161909eb0>,
 4: <neat.genes.DefaultNodeGene at 0x7fa1505c3370>,
 5: <neat.genes.DefaultNodeGene at 0x7fa1505c1a60>,
 6: <neat.genes.DefaultNodeGene at 0x7fa1505c3730>,
 7: <neat.genes.DefaultNodeGene at 0x7fa1505c3a30>}

In [20]:
node_tracker = {node_id:{'depth':0, 'output_ids':[], 'input_ids':[]} for node_id in h.nodes}
for node_id in p.config.genome_config.input_keys:
    node_tracker[node_id] = {'depth':0, 'output_ids':[], 'input_ids':[]}
trace_stack = [node_id for node_id in p.config.genome_config.input_keys]

In [21]:
trace_stack

[-1, -2]

In [22]:
node_tracker

{0: {'depth': 0, 'output_ids': [], 'input_ids': []},
 1: {'depth': 0, 'output_ids': [], 'input_ids': []},
 4: {'depth': 0, 'output_ids': [], 'input_ids': []},
 5: {'depth': 0, 'output_ids': [], 'input_ids': []},
 6: {'depth': 0, 'output_ids': [], 'input_ids': []},
 7: {'depth': 0, 'output_ids': [], 'input_ids': []},
 -1: {'depth': 0, 'output_ids': [], 'input_ids': []},
 -2: {'depth': 0, 'output_ids': [], 'input_ids': []}}

In [23]:
for connection in h.connections:
    print(connection)
    node_tracker[connection[0]]['output_ids'].append(connection[1])
    node_tracker[connection[1]]['input_ids'].append(connection[0])

(-1, 0)
(-2, 1)
(1, 0)
(-2, 4)
(4, 1)
(-2, 5)
(5, 1)
(1, 6)
(6, 0)
(6, 7)
(7, 0)
(-1, 4)
(4, 7)
(4, 6)


In [24]:
while len(trace_stack) > 0:
    trace = trace_stack[0]
    my_depth = node_tracker[trace]['depth']
    next_depth = my_depth + 1
    for output_id in node_tracker[trace]['output_ids']:
        node_tracker[output_id]['depth'] = max(node_tracker[output_id]['depth'], next_depth)
        trace_stack.append(output_id)
    del(trace_stack[0])

In [25]:
node_tracker

{0: {'depth': 5, 'output_ids': [], 'input_ids': [-1, 1, 6, 7]},
 1: {'depth': 2, 'output_ids': [0, 6], 'input_ids': [-2, 4, 5]},
 4: {'depth': 1, 'output_ids': [1, 7, 6], 'input_ids': [-2, -1]},
 5: {'depth': 1, 'output_ids': [1], 'input_ids': [-2]},
 6: {'depth': 3, 'output_ids': [0, 7], 'input_ids': [1, 4]},
 7: {'depth': 4, 'output_ids': [0], 'input_ids': [6, 4]},
 -1: {'depth': 0, 'output_ids': [0, 4], 'input_ids': []},
 -2: {'depth': 0, 'output_ids': [1, 4, 5], 'input_ids': []}}

In [26]:
for node_id, node in node_tracker.items():
    node['output_layers']=[]
    node['needs_skip'] = False
    node['id'] = node_id
    for output_id in node['output_ids']:
        node['output_layers'].append(node_tracker[output_id]['depth'])
        if node_tracker[output_id]['depth'] > (node['depth']+1):
            node['needs_skip'] = True

Create input layer definitions

In [27]:
for node_id, node in node_tracker.items():
    node['input_layers'] = []
    node['skip_layer_input'] = False
    for input_id in node['input_ids']:
        node['input_layers'].append(node_tracker[input_id]['depth'])
        if node_tracker[input_id]['depth'] < (node['depth']-1):
            node['skip_layer_input'] = True

In [28]:
node_tracker

{0: {'depth': 5,
  'output_ids': [],
  'input_ids': [-1, 1, 6, 7],
  'output_layers': [],
  'needs_skip': False,
  'id': 0,
  'input_layers': [0, 2, 3, 4],
  'skip_layer_input': True},
 1: {'depth': 2,
  'output_ids': [0, 6],
  'input_ids': [-2, 4, 5],
  'output_layers': [5, 3],
  'needs_skip': True,
  'id': 1,
  'input_layers': [0, 1, 1],
  'skip_layer_input': True},
 4: {'depth': 1,
  'output_ids': [1, 7, 6],
  'input_ids': [-2, -1],
  'output_layers': [2, 4, 3],
  'needs_skip': True,
  'id': 4,
  'input_layers': [0, 0],
  'skip_layer_input': False},
 5: {'depth': 1,
  'output_ids': [1],
  'input_ids': [-2],
  'output_layers': [2],
  'needs_skip': False,
  'id': 5,
  'input_layers': [0],
  'skip_layer_input': False},
 6: {'depth': 3,
  'output_ids': [0, 7],
  'input_ids': [1, 4],
  'output_layers': [5, 4],
  'needs_skip': True,
  'id': 6,
  'input_layers': [2, 1],
  'skip_layer_input': True},
 7: {'depth': 4,
  'output_ids': [0],
  'input_ids': [6, 4],
  'output_layers': [5],
  'need

In [29]:
layers = {}
for node_id, node in node_tracker.items():
    if not node['depth'] in layers:
        layers[node['depth']] = {
            'nodes':{node_id:node}
        }
    else:
        layers[node['depth']]['nodes'][node_id] = node
        
# Ensure all nodes have a layer index
for layer_id, layer in layers.items():
    layer_index = 0
    for node_id, node in layer['nodes'].items():
        node['layer_index'] = layer_index
        layer_index += 1
        
        
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-1, 1, 6, 7],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 2, 3, 4],
    'skip_layer_input': True,
    'layer_index': 0}}},
 2: {'nodes': {1: {'depth': 2,
    'output_ids': [0, 6],
    'input_ids': [-2, 4, 5],
    'output_layers': [5, 3],
    'needs_skip': True,
    'id': 1,
    'input_layers': [0, 1, 1],
    'skip_layer_input': True,
    'layer_index': 0}}},
 1: {'nodes': {4: {'depth': 1,
    'output_ids': [1, 7, 6],
    'input_ids': [-2, -1],
    'output_layers': [2, 4, 3],
    'needs_skip': True,
    'id': 4,
    'input_layers': [0, 0],
    'skip_layer_input': False,
    'layer_index': 0},
   5: {'depth': 1,
    'output_ids': [1],
    'input_ids': [-2],
    'output_layers': [2],
    'needs_skip': False,
    'id': 5,
    'input_layers': [0],
    'skip_layer_input': False,
    'layer_index': 1}}},
 3: {'nodes': {6: {'depth': 3,
    'output_ids': [0, 7],
    'input_ids': [1,

In [30]:

LAYER_TYPE_CONNECTED = "CONNECTED"
LAYER_TYPE_INPUT = "INPUT"
LAYER_TYPE_OUTPUT = "OUTPUT"
for layer_id, layer in layers.items():
    layer['is_output_layer'] = False
    layer['is_input_layer'] = False
    layer['layer_type'] = LAYER_TYPE_CONNECTED
    # If I have the output node in me, then I am an output
    if 0 in layer['nodes']:
        layer['is_output_layer'] = True
        layer['layer_type'] = LAYER_TYPE_OUTPUT

    # If I have the first input in me, then I am the input
    if -1 in layer['nodes']:
        layer['is_input_layer'] = True
        layer['layer_type'] = LAYER_TYPE_INPUT
    biases = []

    layer['input_layers'] = []
    ## Compute the shape of required inputs
    for node_id, node in layer['nodes'].items():
        for in_layer in node['input_layers']:
            if in_layer not in layer['input_layers']:
                layer['input_layers'].append(in_layer)
    layer['input_layers'].sort()
    layer['input_shape'] = sum(len(layers[jj]['nodes']) for jj in layer['input_layers'])
    layer['weights_shape'] = (layer['input_shape'], len(layer['nodes']))


    # Handle output layer "edge" case
    if layer['is_output_layer']:
        layer['out_weights'] = []
        layer['bias'] = [h.nodes[node_id].bias for node_id, node in layer['nodes'].items()]
        layer['in_weights'] = [[0 for __ in layers[layer_id-1]['nodes']] for _ in layer['nodes']]
    # Handle input layer "edge" case
    elif layer['is_input_layer']:
        layer['in_weights'] = []
        layer['bias'] = []
        layer['out_weights'] = [[0 for __ in layers[layer_id+1]['nodes']] for _ in layer['nodes']]
    # Handle generic case
    else:
        layer['out_weights'] = [[0 for __ in layers[layer_id+1]['nodes']] for _ in layer['nodes']]
        layer['in_weights'] = [[0 for __ in layers[layer_id-1]['nodes']] for _ in layer['nodes']]

        layer['bias'] = [h.nodes[node_id].bias for node_id, node in layer['nodes'].items()]
        # else:
            # layer['bias'] = [0 for _ in layer['nodes']]
    
    layer_index = 0          
    for node_id, node in layer['nodes'].items():
        node['layer_index'] = layer_index
        layer_index += 1

#################################################
#################################################
#################################################
        ### POSSIBLY NEED THIS
        # if node['id'] < 0:
        #     biases.append(1)
        # else:
        #     biases.append(h.nodes[node['id']].bias)
        # for output_id in node['output_ids']:
        #     if (node['id'], output_id) in h.connections:
        #         if output_id in layers[layer_id + 1]['nodes']:
        #             layer['out_weights'][node['layer_index']][layers[layer_id + 1]['nodes'][output_id]['layer_index']] = h.connections[(node['id'], output_id)].weight
        #         else:
        #             # TODO: this is a skip layer to deal with
        #             pass
        #     else:
        #         # this is not a connection that exists, so default of 0 holds
        #         pass
        # for input_id in node['input_ids']:
        #     if (input_id, node['id']) in h.connections:
        #         if input_id in layers[layer_id - 1]['nodes']:
        #             layer['in_weights'][node['layer_index']][layers[layer_id -1]['nodes'][input_id]['layer_index']] = h.connections[(input_id, node['id'])].weight
        #         else:
        #             # TODO: this is a skip layer to deal with
        #             pass
        #     else:
        #         # this is not a connection that exists, so default of 0 holds
        #         pass
        #################################################
            ### END OF POSSIBLY NEEDING THIS
    #################################################
    #################################################
    #################################################
    #################################################


    # layer['out_tensor'] = torch.tensor(layer['out_weights'])
    # layer['bias'] = torch.tensor(layer['bias'])
    # layer['out_tensor_shape'] = layer['out_tensor'].shape
    # layer['in_tensor'] = torch.tensor(layer['in_weights'])
    # layer['in_tensor_shape'] = layer['in_tensor'].shape



    # Set up current weights
    layer['input_weights'] = np.zeros(layer['weights_shape'])
    layer_offset = 0
    # Check every layer and every node for connections
    print("my layer id is %s" % (layer_id))
    for input_layer_id in layer['input_layers']:
        input_layer = layers[input_layer_id]
        for node_id, node in input_layer['nodes'].items():
            for node_output_id in node['output_ids']:
                if node_output_id in layer['nodes']:
                    node_output = layer['nodes'][node_output_id]
                    # I HAVE THIS NODE!
                    # What is it's weight?
                    connection = h.connections[(node_id, node_output_id)]
                    print(connection)

                    if not connection.enabled:
                        continue
                    connection_weight = connection.weight
                    print(connection_weight)

                    in_weight_location = layer_offset + node['layer_index']
                    out_weight_location = node_output['layer_index']
                    print('location is')
                    print((out_weight_location, in_weight_location))
                    layer['input_weights'][in_weight_location][out_weight_location] = connection_weight
        layer_offset += len(input_layer['nodes'])

my layer id is 5
DefaultConnectionGene(key=(-1, 0), weight=-0.1703117936849594, enabled=True)
-0.1703117936849594
location is
(0, 0)
DefaultConnectionGene(key=(1, 0), weight=0.1489894688129425, enabled=False)
DefaultConnectionGene(key=(6, 0), weight=0.1489894688129425, enabled=False)
DefaultConnectionGene(key=(7, 0), weight=0.1489894688129425, enabled=True)
0.1489894688129425
location is
(0, 4)
my layer id is 2
DefaultConnectionGene(key=(-2, 1), weight=0.5530250668525696, enabled=False)
DefaultConnectionGene(key=(4, 1), weight=0.5530250668525696, enabled=True)
0.5530250668525696
location is
(0, 2)
DefaultConnectionGene(key=(5, 1), weight=0.5530250668525696, enabled=True)
0.5530250668525696
location is
(0, 3)
my layer id is 1
DefaultConnectionGene(key=(-1, 4), weight=0.9151367334505461, enabled=True)
0.9151367334505461
location is
(0, 0)
DefaultConnectionGene(key=(-2, 4), weight=1.0, enabled=True)
1.0
location is
(0, 1)
DefaultConnectionGene(key=(-2, 5), weight=1.0, enabled=True)
1.0
lo

In [31]:
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-1, 1, 6, 7],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 2, 3, 4],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 2, 3, 4],
  'input_shape': 5,
  'weights_shape': (5, 1),
  'out_weights': [],
  'bias': [-0.4006558060646057],
  'in_weights': [[0]],
  'input_weights': array([[-0.17031179],
         [ 0.        ],
         [ 0.        ],
         [ 0.        ],
         [ 0.14898947]])},
 2: {'nodes': {1: {'depth': 2,
    'output_ids': [0, 6],
    'input_ids': [-2, 4, 5],
    'output_layers': [5, 3],
    'needs_skip': True,
    'id': 1,
    'input_layers': [0, 1, 1],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0, 1],
  'input_shape': 4,
  'weights_shape': (4

Add in computation of skip layers

In [32]:
layers[2]

{'nodes': {1: {'depth': 2,
   'output_ids': [0, 6],
   'input_ids': [-2, 4, 5],
   'output_layers': [5, 3],
   'needs_skip': True,
   'id': 1,
   'input_layers': [0, 1, 1],
   'skip_layer_input': True,
   'layer_index': 0}},
 'is_output_layer': False,
 'is_input_layer': False,
 'layer_type': 'CONNECTED',
 'input_layers': [0, 1],
 'input_shape': 4,
 'weights_shape': (4, 1),
 'out_weights': [[0]],
 'in_weights': [[0, 0]],
 'bias': [1.2642592191696167],
 'input_weights': array([[0.        ],
        [0.        ],
        [0.55302507],
        [0.55302507]])}

In [33]:
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-1, 1, 6, 7],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 2, 3, 4],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 2, 3, 4],
  'input_shape': 5,
  'weights_shape': (5, 1),
  'out_weights': [],
  'bias': [-0.4006558060646057],
  'in_weights': [[0]],
  'input_weights': array([[-0.17031179],
         [ 0.        ],
         [ 0.        ],
         [ 0.        ],
         [ 0.14898947]])},
 2: {'nodes': {1: {'depth': 2,
    'output_ids': [0, 6],
    'input_ids': [-2, 4, 5],
    'output_layers': [5, 3],
    'needs_skip': True,
    'id': 1,
    'input_layers': [0, 1, 1],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0, 1],
  'input_shape': 4,
  'weights_shape': (4

The question is, how do you code the operations to dynamically create the
NN? You need to be able to do the right things in the right order. You have
a list of possible operations:
* Matrix multiple
* Concatenate (for skip layers)
* Matrix addition (for biases)
* Output

The order of operations in each layer is:

1. Concatenate input tensors
2. Matrix multiply input tensors with weights
3. Add bias tensors
4. Apply activation function

I.e., `output = f(cat(inputs) + bias)` for a given activation function f

These computations can be computed back-to-front, and then executed forward

In [34]:
ACTIVATE_OPERATION = "ACTIVATE"
OUTPUT_OPERATION = "OUTPUT"
TENADD_OPERATION = "TENADD" # Tensor ADD
ADD_BIAS_OPERATION = "BIASADD"
TENMUL_OPERATION = "TENMUL"
TENCAT_OPERATION = "TENCAT"
order_of_operations = []

# for layer_id, layer in layers.items():
#     print(layer)
#     # Output for final layer
#     if layer['is_output_layer']:
#         order_of_operations.append(OUTPUT_OPERATION)
#     # Activate
#     order_of_operations.append(ACTIVATE_OPERATION)
#     # Add Bias
#     order_of_operations.append(ADD_BIAS_OPERATION)
#     # Matrix Multiply weights

    


#     print(order_of_operations)

#     break

for layer_id in range(len(layers)):
    layer = layers[layer_id]
    print(layer)

{'nodes': {-1: {'depth': 0, 'output_ids': [0, 4], 'input_ids': [], 'output_layers': [5, 1], 'needs_skip': True, 'id': -1, 'input_layers': [], 'skip_layer_input': False, 'layer_index': 0}, -2: {'depth': 0, 'output_ids': [1, 4, 5], 'input_ids': [], 'output_layers': [2, 1, 1], 'needs_skip': True, 'id': -2, 'input_layers': [], 'skip_layer_input': False, 'layer_index': 1}}, 'is_output_layer': False, 'is_input_layer': True, 'layer_type': 'INPUT', 'input_layers': [], 'input_shape': 0, 'weights_shape': (0, 2), 'in_weights': [], 'bias': [], 'out_weights': [[0, 0], [0, 0]], 'input_weights': array([], shape=(0, 2), dtype=float64)}
{'nodes': {4: {'depth': 1, 'output_ids': [1, 7, 6], 'input_ids': [-2, -1], 'output_layers': [2, 4, 3], 'needs_skip': True, 'id': 4, 'input_layers': [0, 0], 'skip_layer_input': False, 'layer_index': 0}, 5: {'depth': 1, 'output_ids': [1], 'input_ids': [-2], 'output_layers': [2], 'needs_skip': False, 'id': 5, 'input_layers': [0], 'skip_layer_input': False, 'layer_index': 1

In [35]:
a = torch.randn(2,3)
b = torch.randn(3, 1)
c = torch.matmul(a, b)

In [36]:
c

tensor([[ 3.5621],
        [-0.6318]])

In [37]:
layers

{5: {'nodes': {0: {'depth': 5,
    'output_ids': [],
    'input_ids': [-1, 1, 6, 7],
    'output_layers': [],
    'needs_skip': False,
    'id': 0,
    'input_layers': [0, 2, 3, 4],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': True,
  'is_input_layer': False,
  'layer_type': 'OUTPUT',
  'input_layers': [0, 2, 3, 4],
  'input_shape': 5,
  'weights_shape': (5, 1),
  'out_weights': [],
  'bias': [-0.4006558060646057],
  'in_weights': [[0]],
  'input_weights': array([[-0.17031179],
         [ 0.        ],
         [ 0.        ],
         [ 0.        ],
         [ 0.14898947]])},
 2: {'nodes': {1: {'depth': 2,
    'output_ids': [0, 6],
    'input_ids': [-2, 4, 5],
    'output_layers': [5, 3],
    'needs_skip': True,
    'id': 1,
    'input_layers': [0, 1, 1],
    'skip_layer_input': True,
    'layer_index': 0}},
  'is_output_layer': False,
  'is_input_layer': False,
  'layer_type': 'CONNECTED',
  'input_layers': [0, 1],
  'input_shape': 4,
  'weights_shape': (4

In [38]:
x_input = nn.Parameter(torch.tensor([0.3, 0.4], dtype=torch.float64))

In [39]:
class Net(nn.Module):
    def __init__(self, layers):
        super(Net, self).__init__()  # just run the init of parent class (nn.Module)
        self.weights = {layer_id: self._tt(layer['input_weights'].copy()) for layer_id, layer in layers.items()}
        self.biases = {layer_id: self._tt(layer['bias'].copy()) for layer_id, layer in layers.items()}
        self.layer_types = {layer_id: layer['layer_type'] for layer_id, layer in layers.items()}
        self.layer_inputs = {layer_id: layer['input_layers'] for layer_id, layer in layers.items()}
        self.n_layers = len(layers)

        self._outputs = None

        for w_id, w in self.weights.items():
            self.register_parameter(name ="weight_%s"%w_id, param=w)

        for b_id, b in self.biases.items():
            self.register_parameter(name = "bias_%s"%b_id, param=b)

        # x = F.relu(self.fc1(x))

        # self.fc2 = nn.Linear(512, 10)

    @staticmethod
    def _tt(mat):
        return torch.nn.Parameter(torch.tensor(mat,dtype=torch.float64), requires_grad=True)
    def forward(self, x):
        # print("running forward")
        self._outputs = {}
        for layer_id in range(self.n_layers):
            layer_input = None
            layer_type = self.layer_types[layer_id]

            # print(layer_id)
            # print(layer_type)

            if layer_type == LAYER_TYPE_INPUT:
                self._outputs[layer_id] = x
                continue
            if layer_type == LAYER_TYPE_CONNECTED:
                layer_input = torch.cat([self._outputs[ii] for ii in self.layer_inputs[layer_id]])
            if layer_type == LAYER_TYPE_OUTPUT:
                layer_input = torch.cat([self._outputs[ii] for ii in self.layer_inputs[layer_id]])

            # print(layer_input)
            # print(self.weights[layer_id])
            # print(self.biases[layer_id])

            self._outputs[layer_id] = torch.sigmoid( torch.matmul(layer_input, self.weights[layer_id]) + self.biases[layer_id] )

            if layer_type == LAYER_TYPE_OUTPUT:
                return self._outputs[layer_id]


In [40]:
net = Net(layers)

In [41]:
net.biases

{5: Parameter containing:
 tensor([-0.4007], dtype=torch.float64, requires_grad=True),
 2: Parameter containing:
 tensor([1.2643], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([-0.8664,  2.4587], dtype=torch.float64, requires_grad=True),
 3: Parameter containing:
 tensor([-1.1083], dtype=torch.float64, requires_grad=True),
 4: Parameter containing:
 tensor([0.0338], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], dtype=torch.float64, requires_grad=True)}

In [42]:
net._outputs

In [43]:
result = net.forward(x_input)
result

tensor([0.4130], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [44]:
expected_result = torch.tensor(xor(x_input[0], x_input[1]))
expected_result

tensor(0.)

In [45]:
learning_rate = 0.1
# x_input = torch.randn(1, 1, 2, dtype=torch.float64)
with MethodTimer('benchmark'):

    for k in range(25):
        for n in range(400):
            x_input = nn.Parameter(torch.tensor([np.random.rand(), np.random.rand()], dtype=torch.float64))


            result = net.forward(x_input)
            expected_result = torch.tensor(xor(x_input[0], x_input[1]), dtype=torch.float64)
            # print(x_input)
            # print(expected_result)
            # print(result)
            loss_fn = torch.nn.MSELoss(reduction='sum')
            loss = loss_fn(result, expected_result)
            net.zero_grad()
            loss.backward()
            with torch.no_grad():
                # for parameter in net.parameters():
                    # parameter.data -= learning_rate*parameter.grad.data
                    # weight -= learning_rate * weight.grad
                for  w_id, weight in net.weights.items():
                    try:
                        weight -= learning_rate * weight.grad
                    except TypeError:
                        continue
                for  b_id, bias in net.biases.items():
                    try:
                        bias -= learning_rate * bias.grad
                    except TypeError:
                        continue





The function - benchmark - has just started at 1615094972.375127
The function - benchmark - took 5.074125051498413 seconds to complete


In [46]:
# net(torch.tensor(xor_inputs, dtype=torch.float64))

In [47]:
net.biases[1].grad

tensor([-0.0018,  0.0001], dtype=torch.float64)

In [48]:
result

tensor([0.5856], dtype=torch.float64, grad_fn=<SigmoidBackward>)

In [49]:
optimizer = optim.SGD(net.parameters(), lr=0.01, momentum=0.9)


In [50]:
optimizer.zero_grad()
output = net(x_input)
loss = loss_fn(result, expected_result)


In [51]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[0.2662],
        [0.0670],
        [0.2475],
        [0.0657],
        [0.2496]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.1673],
        [-0.1798],
        [ 0.3681],
        [ 0.1978]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.9123, -0.0033],
        [ 0.9923,  0.9991]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.0805],
        [-0.2828],
        [ 0.7490]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.3443],
        [-0.3593],
        [ 0.8709]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0767], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.8895], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.8925,  2.4565], dtype=torch.float64, requires_grad=True)
Parame

In [52]:
myW = net.weights[1]

In [53]:
myW

Parameter containing:
tensor([[ 0.9123, -0.0033],
        [ 0.9923,  0.9991]], dtype=torch.float64, requires_grad=True)

In [54]:
loss

tensor(0.1717, dtype=torch.float64, grad_fn=<MseLossBackward>)

In [55]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[0.2662],
        [0.0670],
        [0.2475],
        [0.0657],
        [0.2496]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.1673],
        [-0.1798],
        [ 0.3681],
        [ 0.1978]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.9123, -0.0033],
        [ 0.9923,  0.9991]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.0805],
        [-0.2828],
        [ 0.7490]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[ 0.3443],
        [-0.3593],
        [ 0.8709]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.0767], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([0.8895], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.8925,  2.4565], dtype=torch.float64, requires_grad=True)
Parame

In [56]:
net.weights

{5: Parameter containing:
 tensor([[0.2662],
         [0.0670],
         [0.2475],
         [0.0657],
         [0.2496]], dtype=torch.float64, requires_grad=True),
 2: Parameter containing:
 tensor([[-0.1673],
         [-0.1798],
         [ 0.3681],
         [ 0.1978]], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([[ 0.9123, -0.0033],
         [ 0.9923,  0.9991]], dtype=torch.float64, requires_grad=True),
 3: Parameter containing:
 tensor([[-0.0805],
         [-0.2828],
         [ 0.7490]], dtype=torch.float64, requires_grad=True),
 4: Parameter containing:
 tensor([[ 0.3443],
         [-0.3593],
         [ 0.8709]], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)}

In [57]:
net._outputs

{0: Parameter containing:
 tensor([0.4466, 0.6934], dtype=torch.float64, requires_grad=True),
 1: tensor([0.5506, 0.9588], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 2: tensor([0.7470], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 3: tensor([0.2383], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 4: tensor([0.4274], dtype=torch.float64, grad_fn=<SigmoidBackward>),
 5: tensor([0.5977], dtype=torch.float64, grad_fn=<SigmoidBackward>)}

In [58]:
data = torch.rand(1, 1,2, dtype=torch.float64)
label = [xor(val[0][0], val[0][1]) for val in data]


In [59]:
# net(data)

In [60]:
# I.e., `output = f(cat(inputs) + bias)` for a given activation function f

def forward(layers, x):
    layer_outputs = {}
    curr_value = x
    for ii in range(len(layers)):
        print(ii)
        layer = layers[ii]
        if layer['is_output_layer']:
            # return curr_value
            return(layer_outputs)
        input_layers = [layer_outputs[layer_id] for layer_id in layer['input_layers']]
    return(layer_outputs)
        # layer_outputs[ii] = torch.relu(
        #     torch.add(
        #         torch.matmul(
        #             torch.cat(layer['input_layers']),
        #             layer['weights']

        #         ),
        #         layer['bias']
        #     )
        # )
        # curr_value = torch.sigmoid(torch.matmul(curr_value + layers[ii]['bias'], layers[ii]['out_tensor']) )

In [61]:
# forward(layers, x_input)

In [62]:
h.nodes[0].bias

-0.4006558060646057

In [99]:
with MethodTimer('Parse NNEAT'):
    myNeat = nneat(h, p.config)

The function - Parse NNEAT - has just started at 1615095491.0062232
The function - Parse NNEAT - took 0.0011887550354003906 seconds to complete


In [100]:
myConnection = (-1,0)

In [101]:
h.connections[myConnection].weight

-0.1703117936849594

In [102]:
for param in myNeat.parameters():
    print(param)

Parameter containing:
tensor([[-0.1703],
        [ 0.0000],
        [ 0.0000],
        [ 0.0000],
        [ 0.1490]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.0000],
        [0.0000],
        [0.5530],
        [0.5530]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.9151, 0.0000],
        [1.0000, 1.0000]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.0701],
        [0.0000],
        [1.0000]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.5281],
        [0.0000],
        [1.0000]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.4007], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([1.2643], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.8664,  2.4587], dtype=torch.float64, requires_grad=True)
Parameter conta

In [108]:
learning_rate = 0.1
# x_input = torch.randn(1, 1, 2, dtype=torch.float64)
with MethodTimer('Backprop benchmark (10k inputs)'):

    for k in range(25):
        for n in range(400):
            x_input = nn.Parameter(torch.tensor([np.random.rand(), np.random.rand()], dtype=torch.float64))


            result = myNeat.forward(x_input)
            expected_result = torch.tensor([xor(x_input[0], x_input[1])], dtype=torch.float64)
            # print(x_input)
            # print(expected_result)
            # print(result)
            loss_fn = torch.nn.MSELoss(reduction='sum')
            loss = loss_fn(result, expected_result)
            myNeat.zero_grad()
            loss.backward()
            with torch.no_grad():
                for parameter in myNeat.parameters():
                    try:
                        parameter.data -= learning_rate*parameter.grad.data
                    except AttributeError:
                        continue
                    # weight -= learning_rate * weight.grad
                # for  w_id, weight in net.weights.items():
                #     try:
                #         # print(weight.grad)
                #         weight -= learning_rate * weight.grad
                #     except TypeError:
                #         continue
                # for  b_id, bias in net.biases.items():
                #     try:
                #         bias -= learning_rate * bias.grad
                #     except TypeError:
                #         continue



The function - Backprop benchmark (10k inputs) - has just started at 1615095693.196116
The function - Backprop benchmark (10k inputs) - took 0.0015311241149902344 seconds to complete


AttributeError: 'list' object has no attribute 'size'

In [104]:
for param in myNeat.parameters():
    print(param)

Parameter containing:
tensor([[ 0.6434],
        [ 1.2305],
        [-0.4451],
        [-0.3518],
        [-0.3164]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.8560],
        [-0.8797],
        [-0.3112],
        [-1.2250]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[0.8507, 0.0422],
        [0.9348, 1.0279]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.3604],
        [-0.8499],
        [ 0.4200]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([[-0.1479],
        [-1.3651],
        [ 0.6890]], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-3.3236], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-0.6114], dtype=torch.float64, requires_grad=True)
Parameter containing:
tensor([-1.0203,  2.5215], dtype=torch.float64, requires_grad=True)
Para

In [91]:
myNeat.genome

In [92]:
h.connections[myConnection].weight

-0.1703117936849594

In [93]:
myNeat.genome.connections[myConnection].weight

-0.1703117936849594

In [94]:
myNeat.weights

{5: Parameter containing:
 tensor([[-0.1393],
         [ 0.2148],
         [ 0.0367],
         [-0.0018],
         [ 0.1243]], dtype=torch.float64, requires_grad=True),
 2: Parameter containing:
 tensor([[-0.1744],
         [-0.1848],
         [ 0.3618],
         [ 0.1876]], dtype=torch.float64, requires_grad=True),
 1: Parameter containing:
 tensor([[ 0.9029, -0.0036],
         [ 0.9850,  0.9993]], dtype=torch.float64, requires_grad=True),
 3: Parameter containing:
 tensor([[-0.0801],
         [-0.2856],
         [ 0.7472]], dtype=torch.float64, requires_grad=True),
 4: Parameter containing:
 tensor([[ 0.3380],
         [-0.3733],
         [ 0.8678]], dtype=torch.float64, requires_grad=True),
 0: Parameter containing:
 tensor([], size=(0, 2), dtype=torch.float64, requires_grad=True)}

In [95]:
myNeat.update_genome_weights()

In [96]:
h.connections[myConnection].weight

-0.1703117936849594

In [97]:
myNeat.genome.connections[myConnection].weight

-0.1703117936849594

In [98]:
myNeat.genome.connections[myConnection].new_weight

tensor(-0.1393, dtype=torch.float64, grad_fn=<SelectBackward>)