In [1]:
from __future__ import print_function
import os
import neat
import json

import pandas as pd
import numpy as np
import random

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

import matplotlib.pyplot as plt


from explaneat.core.backprop import NeatNet
from explaneat.core import backprop
from explaneat.core.backproppop import BackpropPopulation
from explaneat.visualization import visualize
from explaneat.core.experiment import ExperimentReporter
from explaneat.core.utility import one_hot_encode


from sklearn import datasets
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report, confusion_matrix


from copy import deepcopy

import time
from datetime import datetime


import gzip
try:
    import cPickle as pickle  # pylint: disable=import-error
except ImportError:
    import pickle  # pylint: disable=import-error

In [2]:

USE_CUDA = torch.cuda.is_available()
USE_CUDA = False
device = torch.device("cuda:1" if USE_CUDA else "cpu")
cuda_device = torch.device("cuda:1" if USE_CUDA else "cpu")

In [3]:
device

device(type='cpu')

In [44]:
cuda_device

device(type='cuda', index=1)

# Iris Experiment

This experiment (a) test the experimental environment, but is also to evaluate the efficacy of the ExplaNEAT algorithm. Speed is a critical factor, as well as stability of results on population size. Total run time will also be measured

First, we need to set a random seed and a total stopping point in the number of generations

In [4]:
my_random_seed = 42
random.seed(my_random_seed)

In [5]:
def one_hot_encode(vals):
    width = max(vals)
    newVals = []
    for val in vals:
        blank = [0. for _ in range(width + 1)]
        blank[val] = 1.
        newVals.append(blank)
    return np.asarray(newVals)


## Dataset

We are going to work with the Iris dataset, which will be loaded from `sklearn`. We want to characterise the efficacy of the algorithm with regards to a mostly untransformed dataset, so we will only normalise the features

In [6]:
iris = datasets.load_iris()
xs_raw = iris.data[:, :]
scaler = StandardScaler()
scaler.fit(xs_raw)
xs = scaler.transform(xs_raw)
ys = iris.target
ys_onehot = one_hot_encode(ys)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(xs, ys, test_size=45, random_state=42)

In [8]:
scaler.inverse_transform([0.,0.,0.,0.])

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [9]:
scaler.inverse_transform([1.,1.,1.,1.])

array([6.66863463, 3.4917443 , 5.51740407, 1.95902596])

In [10]:
scaler.mean_

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [11]:
scaler.scale_

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [12]:
scaler.transform([[0., 0., 0., 3.]])

array([[-7.08024256, -7.03788247, -2.1359505 ,  2.37025687]])

In [13]:
xs_raw.transpose()[2].mean()

3.7580000000000005

In [14]:
# # xs = torch.from_numpy(xs).to(device)
# # ys = torch.from_numpy(ys).to(device)
# X_train = torch.from_numpy(X_train).to(device)
# X_test = torch.from_numpy(X_test).to(device)
# y_train = torch.from_numpy(y_train).to(device)
# y_test = torch.from_numpy(y_test).to(device)

Let's have a look at the data we are working with

In [15]:
xs[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [16]:
ys[:5]

array([0, 0, 0, 0, 0])

In [17]:
ys_onehot[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

## Performance metric

The NEAT implementation on which ExplaNEAT extends uses a single function call for evaluating fitness. Although this might be reworked for ExplaNEAT to be able to get consistency between the genome-evaluation and the backprop loss function, that can be reviewed later.

This use `CrossEntropyLoss` from `PyTorch`

In [18]:
def eval_genomes(genomes, config):
    loss = nn.CrossEntropyLoss()
    loss = loss.to(device)

    for genome_id, genome in genomes:
        net = neat.nn.FeedForwardNetwork.create(genome, config)
        preds = []
        for xi in X_train:
            preds.append(net.activate(xi))
        genome.fitness = float(1./loss(torch.tensor(preds).to(device), torch.tensor(y_train)))

## The competition

In [19]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(X_train, y_train);


In [20]:
# Use the forest's predict method on the test data
rf_preds = rf.predict(X_test)
# Calculate the absolute errors
errors = abs(rf_preds - y_test)

In [21]:
print('Mean Absolute Error:', round(np.mean(errors), 2))

Mean Absolute Error: 0.01


In [22]:
rf_preds

array([1.001, 0.   , 1.995, 1.002, 1.12 , 0.   , 1.   , 1.969, 1.092,
       1.   , 1.955, 0.   , 0.   , 0.   , 0.   , 1.053, 2.   , 1.   ,
       1.001, 2.   , 0.   , 1.921, 0.   , 2.   , 2.   , 1.991, 1.986,
       2.   , 0.   , 0.   , 0.   , 0.   , 1.   , 0.   , 0.   , 1.96 ,
       1.003, 0.   , 0.   , 0.   , 1.983, 1.046, 1.002, 0.   , 0.   ])

In [23]:
errors = abs(rf_preds - y_test)

In [24]:
abs(rf_preds.round(0) - y_test)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')
# Accuracy: 93.99 %.

Accuracy: nan %.


In [26]:
# Importing the classification report and confusion matrix
print(confusion_matrix(y_test,rf_preds.round(0)))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


# SVM

In [27]:
from sklearn.svm import SVC
svm_model=SVC()


In [28]:
svm_model.fit(X_train, y_train)


SVC()

In [29]:
svm_preds=svm_model.predict(X_test)


In [30]:
print(confusion_matrix(y_train, svm_model.predict(X_train).round(0)))

[[31  0  0]
 [ 0 35  2]
 [ 0  2 35]]


In [31]:
# Importing the classification report and confusion matrix
print(confusion_matrix(y_test,svm_preds))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


## Regression

In [32]:
from sklearn.linear_model import LinearRegression
regression_model=LinearRegression()

In [33]:
regression_model.fit(X_train, y_train)

LinearRegression()

In [34]:
pred=regression_model.predict(X_test)

In [35]:
# Importing the classification report and confusion matrix
print(confusion_matrix(y_test,pred.round(0)))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [36]:
regression_model.coef_

array([-0.08874883, -0.025391  ,  0.46581225,  0.40210087])

In [37]:
print(confusion_matrix(y_train, regression_model.predict(X_train).round(0)))

[[31  0  0]
 [ 0 34  3]
 [ 0  1 36]]


# NNs

In [38]:
class NeuralNet(nn.Module):
    def __init__(self, input_size, output_size, hidden_width=64):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_width) 
        self.fc2 = nn.Linear(hidden_width, hidden_width)
        self.fc3 = nn.Linear(hidden_width, hidden_width)
        self.fc4 = nn.Linear(hidden_width, hidden_width)
        self.fc5 = nn.Linear(hidden_width, output_size)  
        
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.relu(out)
        out = self.fc3(out)
        out = self.relu(out)
        out = self.fc4(out)
        out = self.relu(out)
        out = self.fc5(out)
        return out
    
class TabularDataset(Dataset):
    """Face Landmarks dataset."""

    def __init__(self, xs, ys):
        """
        Args:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.xs = xs
        self.ys = ys

    def __len__(self):
        return len(self.xs)

    def __getitem__(self, idx):
        x = self.xs[idx]
        y = self.ys[idx]
        return (x, y)
    


In [39]:
batch_size = 1000
learning_rate = 0.0005
num_epochs = 200

In [43]:
train_data = TabularDataset(X_train, y_train)
train_loader = DataLoader(train_data, 
                           batch_size=batch_size, 
                           shuffle=True)

validate_data = TabularDataset(X_test, y_test)
validate_loader = DataLoader(dataset = validate_data,
                             batch_size=batch_size, 
                             shuffle=False)

total_step = len(train_loader)

my_random_seed = 42
random.seed(my_random_seed)
nn_model = NeuralNet(4, 3).to(cuda_device)

criterion = nn.CrossEntropyLoss().to(cuda_device)
optimizer = torch.optim.Adam(nn_model.parameters(), lr=learning_rate)  
for epoch in range(num_epochs):
    for i, (xsnn, ysnn) in enumerate(train_loader):  
        # Move tensors to the configured device
        xsnn = xsnn.float().to(cuda_device)
        ysnn = ysnn.view(-1, 1).float().to(cuda_device)

        # Forward pass
        outputs = nn_model(xsnn)
        train_loss = criterion(outputs, ysnn)
        

        # Backward and optimize
        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()
        if (epoch+1) % 50 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, train_loss.item()))


AssertionError: Torch not compiled with CUDA enabled

In [41]:
g

NameError: name 'g' is not defined

In [42]:
iris_df = pd.DataFrame(xs_raw, columns=iris.feature_names)
iris_df['label'] = iris.target

In [79]:
iris_df.groupby('label').mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
label                                                           
0                  5.006             3.428              1.462   
1                  5.936             2.770              4.260   
2                  6.588             2.974              5.552   

       petal width (cm)  
label                    
0                 0.246  
1                 1.326  
2                 2.026

In [83]:
scaler.scale_

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [84]:
scaler.mean_

array([5.84333333, 3.05733333, 3.758     , 1.19933333])